{
    'name': 'Fees Management',
    'sequence':7,
    'version': '16.0.1.0.0',
    'summary': 'Fees Management System',
    'category': 'Fees management',
    'depends': ['jt_education_base','product','sale_management','account'],
    'data': [
        'security/fees_security.xml',
        'security/ir.model.access.csv',
        'demo/demo.xml',
        'data/ir_actions_server_data.xml',
        'wizard/pay_yearly_fees_wizard_view.xml',
        'wizard/export_fees_history_wizard_view.xml',
        'wizard/due_fees_summary_report_view.xml',
        'wizard/export_fees_receipt_view.xml',
        'views/student.xml',
        'views/fees_sequence.xml',
        'views/fees_view.xml',
        'views/view_account_move_form.xml',
        'reports/fee_receipt.xml',
    ],
    'application': True,
    'license':'OPL-1',
}
