{
    'name': "Library Management",
    'sequence': 8,
    'version': '16.0.1.0.0',
    'summary': "Library Management System",
    'category': 'Library Management',
    'depends': ['contacts', 'jt_education_base','jt_education_fees'],
    'data': [
        'security/ir.model.access.csv',
        'views/action_and_menu.xml',
        'views/sequence.xml',
        'views/books_view.xml',
        'views/issuebooks_view.xml',
        'views/memberships_view.xml',
        'views/authors_view.xml',
        'views/book_lang.xml',
        'views/student.xml',
        'reports/book_detail_report.xml',
        'reports/issuebook_detail_report.xml',
        'reports/membership_detail_report.xml',
        'reports/membership_card.xml',
        'wizard/book_xls_report_view.xml',
        'wizard/membership_xls_report_view.xml',
        'wizard/issuebook_xls_report_view.xml',
        'data/membership_cron.xml',
        'data/email_template.xml',
        'data/issue_email_cron.xml',
    ],
    'application': True,
    'license':'OPL-1',
}
