{
    'name': "Student Management",
    'sequence':1,
    'summary': "Manage the students details",
    'category': 'Student Extension',
    'version': '16.0.1.0.0',
    'depends': ['contacts','hr_recruitment'],
    'data': [
        'security/base_security.xml',
        'security/ir.model.access.csv',
        'demo/demo.xml',
        'views/student_view.xml',
        'views/district_view.xml',
        'views/village_view.xml',
        'views/student_standard_view.xml',
        'views/faculty_view.xml',
        'views/parent_view.xml',
        'views/how_know.xml',
        'views/action_and_menu.xml',
        'views/sequence.xml',
        'views/admission_inq_view.xml',
    ],
    'application': True,
    'license':'OPL-1',
}
